apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance
  namespace: default
  labels:
    app: attendance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
      - name: attendance
        image: rehan2512/attendance:latest
        args: ["attendance_api:app", "--bind", "0.0.0.0:8081", "--timeout", "60"]
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /attendance/healthz
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /attendance/healthz
            port: 8081
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
